# Generated by Django 3.2.18 on 2024-04-24 19:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_wikicategorysnippet_wikipagewikicategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='The main contents of the page', use_json_field=True, verbose_name='body'),
        ),
    ]
