# Generated by Django 3.2.13 on 2022-06-14 21:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_custome_image_fks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body_markdown',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body_mixed',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='Avoiding this at first because data might be hard to migrate?', verbose_name='body (mixed)'),
        ),
    ]
