# Generated by Django 3.2.14 on 2022-09-14 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('blog', '0012_alter_blogpage_body_mixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='locale',
            field=models.ForeignKey(default='1', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='translation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='blogcategory',
            unique_together={('translation_key', 'locale')},
        ),
    ]
