# Generated by Django 3.2.14 on 2022-10-08 23:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_article_hide_toc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('website', models.URLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name this something, i.e. 'collaborators shown on the main landing page'", max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Organization collection',
                'verbose_name_plural': 'Organization collections',
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('feature', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('sub_headline', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('read_more', wagtail.core.blocks.PageChooserBlock())])), ('carousel', wagtail.core.blocks.StreamBlock([('blog', wagtail.core.blocks.StructBlock([('latest_blog_post', wagtail.core.blocks.BooleanBlock(required=False)), ('blog_post', wagtail.core.blocks.PageChooserBlock(page_type=['blog.BlogPage'], required=False))])), ('page', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.core.blocks.PageChooserBlock())])), ('raw', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('read_more', wagtail.core.blocks.PageChooserBlock())]))], template='home/blocks/carousel.html')), ('section_cards', wagtail.core.blocks.StreamBlock([('section', wagtail.core.blocks.StructBlock([('headline', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))], template='home/blocks/section_cards.html'))], blank=True, help_text='The main contents of the page', verbose_name='body'),
        ),
        migrations.CreateModel(
            name='OrganizationRelation',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.organization')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='home.organizationcollection')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('home.organization', models.Model),
        ),
    ]
