# Generated by Django 3.2.18 on 2023-04-29 20:34

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_organizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('opt_out', models.BooleanField(default=False, help_text="Check this box if a user indicates that they do not want the newsletter so we can avoid sending it to them in the future. However,remember that deleting a user's email is preferable in most cases.")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('feature', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('sub_headline', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('read_more', wagtail.blocks.PageChooserBlock())])), ('carousel', wagtail.blocks.StreamBlock([('blog', wagtail.blocks.StructBlock([('latest_blog_post', wagtail.blocks.BooleanBlock(required=False)), ('blog_post', wagtail.blocks.PageChooserBlock(page_type=['blog.BlogPage'], required=False))])), ('page', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock())])), ('raw', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('headline', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('read_more', wagtail.blocks.PageChooserBlock())]))], template='home/blocks/carousel.html')), ('section_cards', wagtail.blocks.StreamBlock([('section', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('read_more', wagtail.blocks.PageChooserBlock())]))], template='home/blocks/section_cards.html')), ('organizations_card', wagtail.blocks.StructBlock([('headline', wagtail.blocks.CharBlock()), ('sub_headline', wagtail.blocks.CharBlock()), ('organizations', wagtail.snippets.blocks.SnippetChooserBlock('home.OrganizationCollection'))]))], blank=True, help_text='The main contents of the page', use_json_field=None, verbose_name='body'),
        ),
    ]
